// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ds-redesign/Dashboard.tsx": () => import("../components/mockups/ds-redesign/Dashboard.tsx"),
  "./components/mockups/ds-redesign/Home.tsx": () => import("../components/mockups/ds-redesign/Home.tsx"),
  "./components/mockups/ds-redesign/Login.tsx": () => import("../components/mockups/ds-redesign/Login.tsx"),
  "./components/mockups/ds-redesign/Pricing.tsx": () => import("../components/mockups/ds-redesign/Pricing.tsx")
};
